site_name: Dashboard Big Data - Magreb
site_author: Carlos Rivasplata
site_description: Un pipeline de Big Data de extremo a extremo para analizar el desarrollo político-económico en el Magreb.
# URL oficial de tu sitio (Vital para que los enlaces funcionen en GitHub Pages)
site_url: https://CarlosRivasplata.github.io/ejercicios-bigdata/

# Configuración de Directorios
# "docs_dir: ." le dice a MkDocs que los archivos .md y las carpetas (outputs) están AQUÍ mismo, no en una subcarpeta 'docs'.
docs_dir: .
# Excluimos archivos que no queremos en la web final
exclude_docs: |
  *.py
  *.txt
  *.yml
  docker-compose.yml
  LICENSE
  postgres/
  src/
  site/
  .git/
  .github/
  .venv/
  __pycache__/

theme:
  name: material
  language: es
  logo: material/chart-bar
  favicon: material/chart-bar

  palette:
    - scheme: default
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/CarlosRivasplata

nav:
  - Resumen Ejecutivo: 01_README.md
  - Arquitectura de Infraestructura: 02_INFRAESTRUCTURA.md
  - Análisis de Datos y Hallazgos: 03_RESULTADOS.md
  - Discusión Teórica y Preguntas: 05_RESPUESTAS.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # Esto permite que los diagramas Mermaid se rendericen correctamente
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
